package: datashape

platform:
  - linux-64
  - linux-32
  - osx-64
  - win-32
  - win-64

engine:
  - python=2.6
  - python=2.7
  - python=3.3
  - python=3.4

install:
  - conda config --set always_yes true

script:
  - conda build conda.recipe

build_targets:
  files: conda
  channels: main
