package:
  name: datashape
  version: {{ environ.get('GIT_DESCRIBE_TAG', '')}}

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  {% if environ.get('GIT_DESCRIBE_NUMBER', '0') == '0' %}string: py{{ environ.get('PY_VER').replace('.', '') }}_0
  {% else %}string: py{{ environ.get('PY_VER').replace('.', '') }}_{{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}{% endif %}

source:
  git_url: ../

requirements:
  build:
    - python
    - numpy >=1.7
    - multipledispatch >=0.4.7
    - python-dateutil

  run:
    - python
    - numpy >=1.7
    - multipledispatch >=0.4.7
    - python-dateutil

test:
  requires:
    - pytest
    - mock
  commands:
    - py.test -vx --doctest-modules --pyargs datashape


about:
  home: http://datashape.pydata.org
  license: BSD
